# Defaults handlers for role mailman3

- name: restart_mailman3_core
  service:
    name: mailman3
    state: restarted

- name: restart_mailmanweb
  service:
    name: mailmanweb
    state: restarted
